// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/dfioravanti/go-rest/internal/repositories"
	"github.com/dfioravanti/go-rest/internal/services"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	"os"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initSnippetService(dbPool *pgxpool.Pool, logger *slog.Logger) *services.SnippetService {
	snippetPostgresRepository := createSnippetRepository(dbPool)
	snippetService := createSnippetService(snippetPostgresRepository)
	return snippetService
}

func InitApp(dsn string) Application {
	logger := createLogger()
	pool := createDBConnection(dsn, logger)
	snippetService := initSnippetService(pool, logger)
	application := createApplication(pool, logger, snippetService)
	return application
}

// wire.go:

func createLogger() *slog.Logger {
	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
		Level:     slog.LevelDebug,
		AddSource: true,
	}))

	return logger
}

func createDBConnection(dsn string, logger *slog.Logger) *pgxpool.Pool {

	dbPool, err := pgxpool.New(context.Background(), dsn)
	if err != nil {
		logger.Error(err.Error())
	}
	err = dbPool.Ping(context.Background())
	if err != nil {
		logger.Error(err.Error())
	}

	return dbPool

}

func createSnippetRepository(dbPool *pgxpool.Pool) *repositories.SnippetPostgresRepository {
	return repositories.NewSnippetRepository(dbPool)
}

func createSnippetService(repository *repositories.SnippetPostgresRepository) *services.SnippetService {
	return services.NewSnippetService(repository)
}

func createApplication(dbPool *pgxpool.Pool, logger *slog.Logger, snippetService *services.SnippetService) Application {
	return Application{logger, dbPool, snippetService}
}
