// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"
	"os"
)

// Injectors from wire.go:

func InitApp() Application {
	logger := createLogger()
	application := createApplication(logger)
	return application
}

// wire.go:

func createLogger() *slog.Logger {
	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
		Level:     slog.LevelDebug,
		AddSource: true,
	}))

	return logger
}

func createApplication(logger *slog.Logger) Application {
	return Application{logger}
}
